### PR TITLE
added a unified system for RPC and WSS, size control options, and other options in vars file

### PR DESCRIPTION
**Pull request by gadget78**
- unified the WSS, and RPC backend locations,
so only one single domain is needed for both.

- also added a "allow_list" within the `vars` file, so its a little easier to add/remove IP access to the node

### CODE REVIEW

**Comment by TheMainlander** [comment]
Thank you for building and supporting the Community and collaborating with @go140point6, love ya work @gadget78. :)

**Comment by go140point6** [comment]
> * unified the WSS, and RPC backend locations,
>       so only one single domain is needed for both.
> 
>     * also added a "allow_list" within the `vars` file, so its a little easier to add/remove IP access to the node
>       (plus this will be LIVE as soon as the file is edited, no reboots needed)

Initial issue is that nginx throws a fit when i include the .vars in the nginx.conf.  If I refactor it so that nginx likes it, then bash throws a fit.

I'm going to try creating a separate allow_list file that nginx is happy with based on the initial run of the script. I like the idea of having a single file for the allow but not sure I can do it. If I find out how I circle back and fix.

**Comment by gadget78** [comment]
redid lots of this,

and found after much trying, like ya say, nginx didn't like how i setup the allow_list... 
so i have changed the way the allow_list is implemented (the only method is using a separate file)
i wanted all the variables in one, but thats just not an option,
so like you thought, its now a separate file, so does still make it easier than messing within the nginx folder/config files... 

also redid the output of the install process, so its a little clearer to see whats going on etc...

**Comment by gadget78** [comment]
new update,
this was mainly for size support options, 
but it also gives you more options in the .vars file,
for eg, no cert-bot/SSL so its MUCH easier for people that have their node behind an existing front end/nginx
ive made the default "medium", as the default was on medium originally, but it didn't restrict the HDD consumption before.

**Comment by go140point6** [comment]
Complete re-write using this as the PR as the template.  Merged separately.

**Pull request closed without merging**
